name: Issue Wontfix

on:
  issues:
    types: [labeled]

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'wontfix'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, this issue will not be worked on and will be closed.
            你好 @${{ github.event.issue.user.login }}，這不會被處理，將被關閉。
      - name: Close issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
